apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk054-mysql-pvc
  namespace: class-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk054-faiss-pvc
  namespace: class-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
