apiVersion: v1
kind: Secret
metadata:
  name: sk054-hbm-secret
  namespace: class-2
type: Opaque
stringData:
  DB_PASS: "SqlDba-1"
  OPENAI_API_KEY: "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"

